# Generated by Django 5.1 on 2024-08-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название звена сети')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('house_number', models.IntegerField(verbose_name='номер дома')),
                ('chain_level', models.IntegerField(choices=[(0, 'завод'), (1, 'розничная сеть'), (2, 'индивидуальный предприниматель')], verbose_name='уровень сети')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='задолженность перед поставщиком, руб.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailchain', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'звено сети',
                'verbose_name_plural': 'звенья сети',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название продукта')),
                ('product_model', models.CharField(max_length=250, verbose_name='модель продукта')),
                ('release_date', models.DateField(verbose_name='дата выхода продукта')),
                ('retail_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retailchain', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
